### ISSUE TITLE
Hide the DEFAULT CHARSET

### ISSUE THREAD

**Issue by karalabe** [project-iris/iris-java#5]
I see you introduced a default charset for the strings. I don't really see the point of making it public. The public API uses strings for addressing (that it will serialize internally using UTF-8), and the messages are binary blobs, that the user fills as he sees fit. Iris doesn't care about the contents of the blobs, and beside testing I doubt anyone will use textual messages (protobufs are the most probable formats).

If it helps during testing, you could add a constant to the tester classes, but don't litter the public API. :)

**Comment by l0rinc** [comment]
If I add it to the tests, I would repeat it's value. I have changed it to package private, since the tests use the same package.

**Comment by karalabe** [comment]
Not really, because the encoding of the data blobs are completely irrelevant from Iris's point of view and are independent of the strings. In essence, the encoding used within the protocol and the encoding in the tests are semantically different things.

But package private will do just fine.

**Comment by l0rinc** [comment]
I can't rebuild the original String, if I don't know the original encoding.
But you're right, since I can compare byte arrays also, I don't need it in the tests.

**Comment by karalabe** [comment]
Yes, but what I meant, is that the data blobs concern the client of the library and not the binding itself. If the client wishes to put UTF-8 strings into the data blobs, so be it, if protobuf packets, then that is also fine.

I'm just saying that the two encodings (stings vs. the one used in the tests) are not tied together.

**Comment by l0rinc** [comment]
You're right, fixed it
